packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^26
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  react: ^19
  react-dom: ^19
  "@rolldown/plugin-babel": ^0.2.3
  babel-plugin-react-compiler: ^1.0.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
