import type { OverrideMeta } from "../types";

export const monitorMatchers = ["name", "make", "model", "serial"];

export const monitorOverrides: OverrideMeta[] = [
  {
    key: "rr",
    label: "Rotate & Flip",
    description: "Output rotation and flip mode",
    type: "select",
    category: "Monitor",
    range: [0, 7],
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "90°" },
      { value: "2", label: "180°" },
      { value: "3", label: "270°" },
      { value: "4", label: "Flip H" },
      { value: "5", label: "Flip V" },
      { value: "6", label: "90° Flip H" },
      { value: "7", label: "270° Flip H" },
    ],
    appliesTo: ["monitorrule"],
  },
  {
    key: "scale",
    label: "Scale",
    description: "Monitor scale factor",
    type: "float",
    category: "Monitor",
    range: [0.001, 1000.0],
    step: 0.25,
    unit: "×",
    appliesTo: ["monitorrule"],
  },
  {
    key: "x",
    label: "X Position",
    description: "Horizontal position in the output layout",
    type: "integer",
    category: "Monitor",
    range: [-99999, 99999],
    unit: "px",
    appliesTo: ["monitorrule"],
  },
  {
    key: "y",
    label: "Y Position",
    description: "Vertical position in the output layout",
    type: "integer",
    category: "Monitor",
    range: [-99999, 99999],
    unit: "px",
    appliesTo: ["monitorrule"],
  },
  {
    key: "width",
    label: "Width",
    description: "Output width in pixels",
    type: "integer",
    category: "Monitor",
    range: [1, 99999],
    unit: "px",
    appliesTo: ["monitorrule"],
  },
  {
    key: "height",
    label: "Height",
    description: "Output height in pixels",
    type: "integer",
    category: "Monitor",
    range: [1, 99999],
    unit: "px",
    appliesTo: ["monitorrule"],
  },
  {
    key: "refresh",
    label: "Refresh Rate",
    description: "Output refresh rate in Hz",
    type: "float",
    category: "Monitor",
    range: [0.001, 1000.0],
    step: 0.5,
    unit: "Hz",
    appliesTo: ["monitorrule"],
  },
  {
    key: "vrr",
    label: "Variable Refresh Rate",
    description: "Enable VRR (freesync/gsync)",
    type: "boolean",
    category: "Monitor",
    appliesTo: ["monitorrule"],
    aliases: ["freesync", "gsync", "adaptive sync"],
  },
  {
    key: "custom",
    label: "Custom Mode",
    description: "Enable a custom video mode",
    type: "boolean",
    category: "Monitor",
    appliesTo: ["monitorrule"],
  },
];
