import type { OverrideMeta } from "../types";
import { TAG_COUNT_MAX } from "../../dispatchers/types";

export const windowMatchers = ["appid", "title"];

export const windowOverrides: OverrideMeta[] = [
  {
    key: "isfloating",
    label: "Floating",
    description: "Force window to float or tile",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["float", "tiled", "floating mode"],
  },
  {
    key: "isfullscreen",
    label: "Fullscreen",
    description: "Force window into fullscreen mode",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["full screen"],
  },
  {
    key: "isfakefullscreen",
    label: "Fake Fullscreen",
    description: "Force window into fake fullscreen (full geometry, no fullscreen protocol)",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["fake full screen", "borderless"],
  },
  {
    key: "isnoborder",
    label: "No Border",
    description: "Remove window border",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["borderless", "hide border"],
  },
  {
    key: "isnoshadow",
    label: "No Shadow",
    description: "Disable drop shadow for this window",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["hide shadow"],
  },
  {
    key: "isnoradius",
    label: "No Corner Radius",
    description: "Remove corner radius on this window",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["square", "no radius", "sharp corners"],
  },
  {
    key: "focused_opacity",
    label: "Focused Opacity",
    description: "Opacity when the window is focused",
    type: "float",
    category: "Appearance",
    range: [0.0, 1.0],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
    aliases: ["focus opacity", "opacity focus"],
  },
  {
    key: "unfocused_opacity",
    label: "Unfocused Opacity",
    description: "Opacity when the window is not focused",
    type: "float",
    category: "Appearance",
    range: [0.0, 1.0],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
    aliases: ["blur opacity", "inactive opacity"],
  },
  {
    key: "scroller_proportion",
    label: "Scroller Proportion",
    description: "Override proportion for scroller layout (0=inherit)",
    type: "float",
    category: "Appearance",
    range: [0.0, 1.0],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
  },
  {
    key: "scroller_proportion_single",
    label: "Scroller Proportion (Single)",
    description: "Override proportion when only one window is visible (0=inherit)",
    type: "float",
    category: "Appearance",
    range: [0.0, 1.0],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
  },
  {
    key: "allow_csd",
    label: "Allow Client-Side Decoration",
    description: "Allow the application to draw its own titlebar",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["csd", "client side decoration", "no csd"],
  },
  {
    key: "force_fakemaximize",
    label: "Force Fake Maximize",
    description: "Force fake maximize (full geometry, no protocol)",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["fake maximize"],
  },
  {
    key: "force_tearing",
    label: "Force Tearing",
    description: "Allow tearing for this window",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["tearing", "allow tearing"],
  },
  {
    key: "force_tiled_state",
    label: "Force Tiled State",
    description: "Force the window to behave as tiled even when floating",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "isterm",
    label: "Terminal",
    description: "Mark window as a terminal emulator",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["terminal", "is terminal"],
  },
  {
    key: "isnoanimation",
    label: "Disable Animation",
    description: "Disable all window open/close animations",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["no animation", "disable animation"],
  },
  {
    key: "isopensilent",
    label: "Open Silent",
    description: "Don't focus the window when it opens",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["silent open", "no focus on open"],
  },
  {
    key: "istagsilent",
    label: "Tag Silent",
    description: "Don't switch tags when window opens on another tag",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["silent tag"],
  },
  {
    key: "nofocus",
    label: "No Focus",
    description: "Prevent this window from ever receiving focus",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "nofadein",
    label: "No Fade In",
    description: "Disable fade-in animation",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "nofadeout",
    label: "No Fade Out",
    description: "Disable fade-out animation",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "no_force_center",
    label: "No Force Center",
    description: "Don't auto-center floating windows",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "idleinhibit_when_focus",
    label: "Idle Inhibit When Focused",
    description: "Inhibit idle/screensaver when this window is focused",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["idle inhibit", "inhibit idle"],
  },
  {
    key: "noswallow",
    label: "No Swallow",
    description: "Prevent other windows from swallowing into this one",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["no swallow", "prevent swallow"],
  },
  {
    key: "noblur",
    label: "No Blur",
    description: "Disable background blur behind this window or layer",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule", "layerrule"],
    aliases: ["disable blur"],
  },
  {
    key: "ignore_maximize",
    label: "Ignore Maximize",
    description: "Ignore the window's maximize requests",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["no maximize"],
  },
  {
    key: "ignore_minimize",
    label: "Ignore Minimize",
    description: "Ignore the window's minimize requests",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["no minimize", "no iconify"],
  },
  {
    key: "isnosizehint",
    label: "No Size Hint",
    description: "Ignore the window's size hints",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["no size hint", "ignore size"],
  },
  {
    key: "isnamedscratchpad",
    label: "Named Scratchpad",
    description: "Mark as a named scratchpad window",
    type: "boolean",
    category: "Scratchpad & Overlay",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["scratchpad", "named scratchpad"],
  },
  {
    key: "isunglobal",
    label: "Unglobal",
    description: "Show only on the current tag (opposite of global)",
    type: "boolean",
    category: "Scratchpad & Overlay",
    inherit: true,
    appliesTo: ["windowrule"],
  },
  {
    key: "isglobal",
    label: "Global",
    description: "Show on all tags",
    type: "boolean",
    category: "Scratchpad & Overlay",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["show on all tags", "sticky"],
  },
  {
    key: "isoverlay",
    label: "Overlay",
    description: "Render in the overlay layer (always on top)",
    type: "boolean",
    category: "Scratchpad & Overlay",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["always on top", "overlay layer"],
  },
  {
    key: "allow_shortcuts_inhibit",
    label: "Allow Shortcuts Inhibit",
    description: "Let the window inhibit keyboard shortcuts (e.g., games)",
    type: "boolean",
    category: "Input & Shortcuts",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["shortcuts inhibit", "inhibit shortcuts"],
  },
  {
    key: "animation_type_open",
    label: "Open Animation",
    description: "Override the open animation type for this window or layer",
    type: "select",
    category: "Animation",
    options: [
      { value: "", label: "Default (global default)" },
      { value: "zoom", label: "Zoom" },
      { value: "slide", label: "Slide" },
      { value: "fade", label: "Fade" },
      { value: "none", label: "None" },
    ],
    appliesTo: ["windowrule", "layerrule"],
    aliases: ["open anim", "show animation"],
  },
  {
    key: "animation_type_close",
    label: "Close Animation",
    description: "Override the close animation type for this window or layer",
    type: "select",
    category: "Animation",
    options: [
      { value: "", label: "Default (global default)" },
      { value: "zoom", label: "Zoom" },
      { value: "slide", label: "Slide" },
      { value: "fade", label: "Fade" },
      { value: "none", label: "None" },
    ],
    appliesTo: ["windowrule", "layerrule"],
    aliases: ["close anim", "hide animation"],
  },
  {
    key: "globalkeybinding",
    label: "Global Keybinding",
    description:
      "Keyboard shortcut that triggers even when window is not focused (format: Modifier-Keysym, e.g. Super_L-Escape)",
    type: "string",
    category: "Input & Shortcuts",
    pattern: "^[A-Za-z0-9_+]+-[a-zA-Z]+$",
    patternError:
      "Must match format Modifier-Keysym (e.g. Super_L-Escape). Keysym must be alpha-only (no digits).",
    appliesTo: ["windowrule"],
    aliases: ["global shortcut", "keyboard shortcut", "global bind"],
  },
  {
    key: "tags",
    label: "Tags",
    description: `Assign window to a specific tag (1–${TAG_COUNT_MAX})`,
    type: "integer",
    category: "Tags & Monitor",
    range: [1, TAG_COUNT_MAX],
    unit: "",
    appliesTo: ["windowrule"],
    aliases: ["tag assignment", "move to tag"],
  },
  {
    key: "monitor",
    label: "Monitor",
    description: "Move window to a specific monitor by name",
    type: "string",
    category: "Tags & Monitor",
    appliesTo: ["windowrule"],
    aliases: ["send to monitor", "output"],
  },
  {
    key: "offsetx",
    label: "Offset X",
    description: "Floating window horizontal percentage offset",
    type: "integer",
    category: "Geometry",
    range: [-99999, 99999],
    unit: "%",
    appliesTo: ["windowrule"],
  },
  {
    key: "offsety",
    label: "Offset Y",
    description: "Floating window vertical percentage offset",
    type: "integer",
    category: "Geometry",
    range: [-99999, 99999],
    unit: "%",
    appliesTo: ["windowrule"],
  },
  {
    key: "width",
    label: "Width",
    description: "Floating window width ratio (0=inherit)",
    type: "float",
    category: "Geometry",
    range: [0, 99999],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
    aliases: ["window width"],
  },
  {
    key: "height",
    label: "Height",
    description: "Floating window height ratio (0=inherit)",
    type: "float",
    category: "Geometry",
    range: [0, 99999],
    step: 0.05,
    unit: "",
    appliesTo: ["windowrule"],
    aliases: ["window height"],
  },
  {
    key: "shield_when_capture",
    label: "Shield When Capturing",
    description: "Shield (hide) this window when the screen is being captured/recorded",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["shield capture", "hide when recording", "privacy shield"],
  },
  {
    key: "vrr_only_fullscreen",
    label: "VRR Only Fullscreen",
    description: "Only enable Variable Refresh Rate when the window is fullscreen",
    type: "boolean",
    category: "Appearance",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["vrr fullscreen only", "freesync fullscreen only"],
  },
  {
    key: "force_render",
    label: "Force Render",
    description: "Force rendering even when not visible (e.g. for capture)",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["always render", "force redraw", "render while hidden"],
  },
  {
    key: "activation_bypass",
    label: "Activation Bypass",
    description: "Ignore the compositor's activation/focus rules for this window",
    type: "boolean",
    category: "Behaviour",
    inherit: true,
    appliesTo: ["windowrule"],
    aliases: ["bypass activation", "ignore activation", "no activation"],
  },
];
